title: "EcoClimLab"
description: "Forest Ecology and Climate Lab"

url: "https://ecoclimlab.github.io"
baseurl: ""

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

navigation:
  - title: "About"
    url: /about/
